/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gr.kourtzis.dgs.view;

import gr.kourtzis.dgs.entity.Category;
import lombok.Getter;

/**
 *
 * @author Athanasios Kourtzis
 */
@Getter

public class categoryCrudDialog extends javax.swing.JDialog {
    private Category category;
    private boolean saved;
    /**
     * Creates new form categoryCrudDialog
     */
    public categoryCrudDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        saved = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCategoryId = new javax.swing.JLabel();
        textCategoryId = new javax.swing.JTextField();
        labelGenre = new javax.swing.JLabel();
        textGenre = new javax.swing.JTextField();
        labelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        buttonCancel = new javax.swing.JButton();
        buttonConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelCategoryId.setText("Category id");

        textCategoryId.setEditable(false);

        labelGenre.setText("Genre");

        labelDescription.setText("Description");

        textDescription.setColumns(20);
        textDescription.setRows(5);
        jScrollPane1.setViewportView(textDescription);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonConfirm.setText("Save");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCategoryId, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textGenre)
                                .addComponent(textCategoryId)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelDescription)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textCategoryId)
                    .addComponent(labelCategoryId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textGenre)
                    .addComponent(labelGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonConfirm)
                    .addComponent(buttonCancel))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The method gets called when a new category should be created
     * and saved on the database.
     * @param category The category to be created
     * @return Returns true if the category was created or false if the 
     *         user aborts the dialog.
     */
    public boolean showNewDialog(final Category category) {
        textCategoryId.setText("");
        
        prepareFields("Create", true, true);
        return showDialog(category, "Adding a new category");
    }
    
    /**
     * The method updates an existing category in the database
     * @param category The category to be edited.
     * @return True if the category was updated of false if 
     *         the user aborts the dialog.
     */
    public boolean showUpdateDialog(final Category category) {
        prepareFields("Update", true, true);
        return showDialog(category, "Updating an existing category");
    }
    
    /**
     * The method deletes an existing category from the database.
     * @param category The category we want to delete.
     * @return True if the category was successfully deleted or false
     *         if the dialog was aborted.
     */
    public boolean showDeleteDialog(final Category category) {
        prepareFields("Delete", false, false);
        return showDialog(category, "Delete an existing category. Are you sure?");
    }
    
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        saved = false;
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        saved = true;
        readTextFields();
        dispose();
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private boolean showDialog(final Category category, String titleText) {
        setTitle(titleText);
        this.category = category;
        fillTextFields();
        textGenre.requestFocus();
        setVisible(true);
        
        return saved;
    }
    
    private void prepareFields(final String buttonCaption, 
                               boolean genreButtonEnabled,
                               boolean descButtonEnabled) {
        buttonConfirm.setText(buttonCaption);
        textGenre.setEditable(genreButtonEnabled);
        textDescription.setEditable(descButtonEnabled);
        
    }
    
    private void fillTextFields() {
        if(category != null) {
            if (category.getCategoryId() != 0) {
                textCategoryId.setText(String.valueOf(category.getCategoryId()));
            }

            textGenre.setText(category.getGenre());
            textDescription.setText(category.getDescription());
        }
    }
    
    private void readTextFields() {
        if (category != null) {
            category.setGenre(textGenre.getText());
            category.setDescription(textDescription.getText());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCategoryId;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JTextField textCategoryId;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textGenre;
    // End of variables declaration//GEN-END:variables
}
